[features]
seeds = false

[programs.localnet]
chain = "3nizRNsw6gatu67oXhBQaGfFgmabzXUCPYUouucfapFZ"
caller = "BLW5orYzT75AJH174XTcQ5BdWYUzQyxNUT75hDetAoyg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/chain/verify.test.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/chain/caller.test.ts"
