[features]
seeds = false

[programs.localnet]
chain = "9agqAPFMkmekbTT4tcz8NCjL4WT2Ccpu8ayn1SGzVwC3"
caller = "BmmRtz8Zf4rjQgWT643QG2eqHVkXzebSsnR7XipFTrAg"

[programs.devnet]
chain = "9agqAPFMkmekbTT4tcz8NCjL4WT2Ccpu8ayn1SGzVwC3"
caller = "BmmRtz8Zf4rjQgWT643QG2eqHVkXzebSsnR7XipFTrAg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet" # "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/chain/chain.test.ts tests/chain/verify.test.ts tests/chain/caller.test.ts"
