[features]
seeds = false

[programs.localnet]
chain = "4SPgs3L7Ey9VyRuZwx4X3y86LSAZXP2Hhpz9Sps4v3iT"
caller = "BLW5orYzT75AJH174XTcQ5BdWYUzQyxNUT75hDetAoyg"

[programs.devnet]
chain = "4SPgs3L7Ey9VyRuZwx4X3y86LSAZXP2Hhpz9Sps4v3iT"
caller = "BLW5orYzT75AJH174XTcQ5BdWYUzQyxNUT75hDetAoyg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet" # "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha ./tsconfig.json -t 1000000 tests/chain/chain.test.ts tests/chain/verify.test.ts tests/chain/caller.test.ts"
